spring:
    liquibase:
        change-log: classpath:db/liquibase-changelog.xml
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: validate
    datasource:
        url: jdbc:mysql://localhost:3306/margo?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: warehouse
        password: password
    application:
        name: MargoSrvApplication
